CREATE DATABASE  IF NOT EXISTS `lifekey`;
GO
USE `lifekey`;
GO
CREATE LOGIN $MSSQL_USER WITH PASSWORD = 'lifekey';
GO
CREATE USER $MSSQL_USER FOR LOGIN lifekey;
GO
ALTER SERVER ROLE sysadmin ADD MEMBER [lifekey];
GO