#!/usr/bin/env bash
ssh-keyscan -t rsa github.com > /root/.ssh/known_hosts
eval $(ssh-agent -s)
ssh-add /root/.ssh/github
# cd ../indy-sdk/wrappers/nodejs
# npm run prepare
# npm install
# cd ../../../app
# npm install ../indy-sdk/wrappers/nodejs/
npm install