#!/bin/bash
export MSYS_NO_PATHCONV=1
# Multiplatform approach to getting the dockerhost IP
export DOCKERHOST=${APPLICATION_URL-$(docker run --rm --net=host codenvy/che-ip)}
set -e

SCRIPT_HOME="$( cd "$( dirname "$0" )" && pwd )"
export COMPOSE_PROJECT_NAME="${COMPOSE_PROJECT_NAME:-consent-pds}"

# These can optionally be set outside the script, but defaults are here and should work
export RUST_LOG=${RUST_LOG:-trace}
export TEST_POOL_IP=${TEST_POOL_IP:-${DOCKERHOST}}

# =================================================================================================================
# Usage:
# -----------------------------------------------------------------------------------------------------------------
usage () {
  cat <<-EOF

  Usage: $0 [command] [options]

  Commands:

  build - Build the docker images for the project.
          You need to do this first.

  start - Creates the application containers from the built images
          and starts the services based on the docker-compose.yml file. 
  update - Stops the containers, copies updated code and restarts services

  open - Opens the necessary browser tab for the service

  stop - Stops the services.  This is a non-destructive process.  The containers
         are not deleted so they will be reused the next time you run start.
         Ctrl-C can be used for this if in the same shell and script is in the foreground.

  rebuild - Rebuild the docker images - bypasses the docker image cache.

  rm - Remove project containers and any associated volumes (currently there are none).
EOF
exit 1
}
# -----------------------------------------------------------------------------------------------------------------
# Functions:
# -----------------------------------------------------------------------------------------------------------------
deleteVolumes() {
  echo "Stopping and removing any running containers ..."
  docker-compose rm -svf >/dev/null

  _projectName=${COMPOSE_PROJECT_NAME:-docker}

  _pattern="^${_projectName}_\|^docker_"
  _volumes=$(docker volume ls -q | grep ${_pattern})

  if [ ! -z "${_volumes}" ]; then
    echo "Removing project volumes ..."
    echo ${_volumes} |  xargs docker volume rm
  else
    echo "No project volumes exist."
  fi
}
# =================================================================================================================

pushd ${SCRIPT_HOME} >/dev/null

case "$1" in
  start)
      if [ -z "$2" ]; then
        SVCS='mongo indy_pool consent_app'
      else
        shift
        SVCS="$@"
      fi
      docker-compose up -d ${SVCS}
      docker-compose up consent_cli
      docker-compose logs --tail 13 consent_app
    ;;
  open)
      if which open > /dev/null 2>&1 ; then
         OPEN=open
      elif which xdg-open > /dev/null 2>&1 ; then
         OPEN=xdg-open
      elif which gnome-open > /dev/null 2>&1 ; then
         OPEN=gnome-open
      elif which explorer.exe > /dev/null 2>&1 ; then
         # Windows weirdness - but it works
         OPEN=explorer.exe
      else
         echo "Could not find a suitable tool to open your browser.\nYou will need to manually open a browser tab for 10.0.0.5:5000"
      fi

      $OPEN http://10.0.0.5:5000 
    ;;
  stop)
      docker-compose stop
    ;;
  build)
      docker build -t indy-image -f indy.Dockerfile .
      docker build -t consent-pds .
    ;;
  rebuild)
      docker build -t indy-image -f indy.Dockerfile .
      docker-compose build --no-cache
    ;;
  update)
      CONTAINER_ID=$(docker ps -aqf "name=consent_app")
      docker cp src/ ${CONTAINER_ID}:/usr/src/app
      docker cp package.json ${CONTAINER_ID}:/usr/src/app/package.json
      docker build -t consent-pds .
    ;;
  rm)
      deleteVolumes
    ;;
  *)
      usage;;
esac

popd >/dev/null
